# Generated by Django 5.1.6 on 2025-03-13 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REGISTRO_ICA', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('frecuencia_aplicacion', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_catastro', models.CharField(max_length=50, unique=True)),
                ('municipio', models.CharField(max_length=100)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='gestion.productor')),
            ],
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('tipo_cultivo', models.CharField(max_length=100)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viveros', to='gestion.finca')),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('vivero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores', to='gestion.vivero')),
            ],
        ),
    ]
