# Generated by Django 5.1.6 on 2025-03-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoControlHongo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ICA', models.CharField(max_length=50)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('frecuencia_aplicacion', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodo_carencia', models.IntegerField()),
                ('nombre_hongo', models.CharField(max_length=100)),
            ],
        ),
    ]
